name: Label & Comment on Approved PR

on:
  pull_request_review:
    types: [submitted]

jobs:
  approved:
    if: github.event.review.state == 'APPROVED'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            github.issues.getLabel({
              owner: context.repo.owner,
              repo: context.repo.repo,
              name: 'awaiting-review'
            }).then(data => {
              if (data.data) {
                github.issues.createComment({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: context.issue.number,
                  body: `Hi @${context.actor.login}, Since the PR has been approved. To facilitate the gtech team's internal import process, could you please add the 'awaiting-pr-merge' label?
                })
                github.issues.addLabels({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: context.issue.number,
                  labels: ['awaiting-PR-merge']
                })
              }
            })
