name: Auto Label New Issues

on:
  issues:
    types: [opened,edited]

jobs:
  add-label:
    runs-on: ubuntu-latest

    permissions:
      issues: write
      contents: read

    steps:
      - name: Call Label Prediction API and Add Label
        uses: actions/github-script@v7
        with:
          script: |
            const title = context.payload.issue.title;
            const body = context.payload.issue.body || "";
            const encodedTitle = encodeURIComponent(title);
            const encodedBody = encodeURIComponent(body);

            const apiUrl = `https://bazel-triage-bot-dot-gtech-rmi-dev.uc.r.appspot.com/predict_label?title=${encodedTitle}&description=${encodedBody}`;

            const response = await fetch(apiUrl);
            if (!response.ok) {
              await github.rest.issues.addLabels({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: context.issue.number,
                  labels: ['team-OSS'],
                });
              throw new Error(`API request failed: ${response.statusText}`);
            }

            const data = await response.json();
            const label = data.team_label;

            if (!label) {
              console.log("No label returned from API.");
               // Add the label to the issue
              await github.rest.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                labels: ['team-OSS'],
              });
              return;
            }

            // Add the label to the issue
            await github.rest.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              labels: [label],
            });
