name: Update Lockfile

on:
  pull_request:
    types:
      - labeled

jobs:
  update-lockfile:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Bazel
        uses: bazelbuild/bazel@7.0.0
        with:
          bazel-version: '7.0.0'

      - name: Update Lockfile
        if: "contains(github.event.label.name, 'updatelock')"
        run: |
          bazel run //src/test/tools/bzlmod:update_default_lock_file
          bazel mod deps --lockfile_mode=update

